### ISSUE TITLE
menu feedback

### ISSUE THREAD

**Issue by rogersmykenzie** [chrispuppe/foundations-Assessment2#1]
https://github.com/chrispuppe/foundations-Assessment2/blob/ff4ab9cbaf722a7ed05b00c6704013c494bc2af1/menu.js#L73
For these questions you should be using JavaScript's destructuring feature. It's essentially a built in feature for doing what you have.
`let { price } = pizza`
This is nice because its a little bit shorter and we can take multiple properties off the object in one line instead of multiple. e.g
`let { price, category, name } = pizza`

**Comment by chrispuppe** [comment]
Fix completed
