### ISSUE TITLE
employee feedback

### ISSUE THREAD

**Issue by rogersmykenzie** [chrispuppe/foundations-Assessment2#3]
https://github.com/chrispuppe/foundations-Assessment2/blob/ff4ab9cbaf722a7ed05b00c6704013c494bc2af1/employees.js#L96
Take `this` out and this line is good

https://github.com/chrispuppe/foundations-Assessment2/blob/ff4ab9cbaf722a7ed05b00c6704013c494bc2af1/employees.js#L96
Take `this` out here too. `this` can be referenced anywhere in a JS file, the context in which you reference it determines what its value is. Since we are in a class JS is smart enough to know we are talking about the object being created by the class.

https://github.com/chrispuppe/foundations-Assessment2/blob/ff4ab9cbaf722a7ed05b00c6704013c494bc2af1/employees.js#L99
Move curly brace from line 106 to here, that way the `getEmployees` and `addEmployee` methods are outside the constructor

https://github.com/chrispuppe/foundations-Assessment2/blob/ff4ab9cbaf722a7ed05b00c6704013c494bc2af1/employees.js#L100-L105
This should work fine if you uncomment it with the above changes!

**Comment by chrispuppe** [comment]
Thanks for the help, this helped me get it working and I was also missing a ')' in there that was causing issues too.
